language: ruby
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler -v 1.17.3

rvm:
  - 2.4.9
  - 2.5.8
  - 2.6.6
  - 2.7.1

script:
  - bundle exec rspec spec
