language: ruby
sudo: false
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler -v 1.17.3

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

script:
  - bundle exec rspec spec
