# frozen_string_literal: true
# A sample Guardfile
# Guard-HamlLint supports a lot options with default values:
# all_on_start: true        # Check all files at Guard startup. default: true
# haml_dires: ['app/views'] # Check Directories. default: 'app/views' or '.'
# cli: '--fail-fast --no-color' # Additional command line options to haml-lint.
guard :haml_lint do
  watch(%r{.+\.html.*\.haml$})
  watch(%r{(?:.+/)?\.haml-lint\.yml$}) { |m| File.dirname(m[0]) }
end
